urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
import django.views.static as django_static_view

from recruit_app import views

urlpatterns = [

	# Media URL's
    url(r'^site_media/(?P<path>.*)$', django_static_view.serve, {'document_root': settings.MEDIA_ROOT }),
    url(r'^static/admin/(?P<path>.*)$', django_static_view.serve, {'document_root': settings.STATIC_ROOT }),

    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^confirmation/$', views.confirmation, name="confirmation"),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^signout/$', views.signout, name="signout"),
    url(r'^applications/list/$', views.admin_recruit_application_list, name="admin_recruit_application_list"),
    url(r'^application/update/status/$', views.admin_recruit_application_update_status, name="admin_recruit_application_update_status")
    
    
]

recruit_app/models.py
# -*- coding: utf-8 -*-

from django.db import models

APPLICATION_STATUS = (('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected'))

class RecruitApplication(models.Model):
    name = models.CharField(max_length=140)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    years_of_experience = models.IntegerField(default=0)
    status = models.CharField(max_length=10, default='PENDING', choices=APPLICATION_STATUS)
    created_on     = models.DateTimeField(auto_now_add=True)
    updated_on     = models.DateTimeField(auto_now=True)
       
    def __unicode__(self):
        return "%s" %(self.name)

recruit_app/views.py
# -*- coding: utf-8 -*-

# From python
import sys
import json


# From django
from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, HttpResponse

from app_forms import *
import recruit_api

login_url = settings.LOGIN_URL


def _fn():
    '''
    returns current function name
    '''
    func_name = sys._getframe(1).f_code.co_name
    return func_name


def home(request):
    fn = _fn()
    template_name = fn+".html"
    try:
        form = RecruitApplicationForm()

        if request.method == "POST":
            form = RecruitApplicationForm(request.POST)
            if form.is_valid():
                result = recruit_api.save_application(request, form)
                return HttpResponseRedirect(reverse('confirmation'))

    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return render(request, template_name, locals())


def confirmation(request):
    fn = _fn()
    template_name = fn+".html"
    try:
        pass
    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return render(request, template_name, locals())



def signin(request):
    fn = _fn()
    template_name = fn+".html"
    try:
        form = SigninForm()
        if request.method == "POST":
            form = SigninForm(request.POST)
            if form.is_valid():
                result = recruit_api.signin(request, request.POST.copy())
                return HttpResponseRedirect(reverse('admin_recruit_application_list'))
    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return render(request, template_name, locals())


def signout(request):
    try:
        recruit_api.signout(request)
    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return HttpResponseRedirect(reverse('home'))


@login_required(login_url=login_url)
@user_passes_test(lambda u: u.is_superuser)
def admin_recruit_application_list(request):
    fn = _fn()
    template_name = fn+".html"
    try:
        result, recruit_applications = recruit_api.list_all_applications(request)
    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return render(request, template_name, locals())


@login_required(login_url=login_url)
@user_passes_test(lambda u: u.is_superuser)
def admin_recruit_application_update_status(request):
    try:
        result, recruit_obj = recruit_api.update_application_status(request, request.POST.copy())
    except Exception, e:
        print "Error at line no :%s, %s"%(sys.exc_traceback.tb_lineno, e)
    return HttpResponse(json.dumps(recruit_obj))

crispy_forms/templates/bootstrap/accordion-group.html
<div class="accordion-group">
    <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#{{ div.data_parent }}" href="#{{ div.css_id }}">{{ div.name }}</a>
    </div>
    <div id="{{ div.css_id }}" class="accordion-body collapse{% if div.active %} in{% endif %}" >
        <div class="accordion-inner">
            {{ fields|safe }}
        </div>
    </div>
</div>

crispy_forms/templates/bootstrap/accordion.html
<div class="accordion" id="{{ accordion.css_id }}">
    {{ content|safe }}
</div>

crispy_forms/templates/bootstrap/betterform.html
{% for fieldset in form.fieldsets %}
    <fieldset class="fieldset-{{ forloop.counter }} {{ fieldset.classes }}">
        {% if fieldset.legend %}
            <legend>{{ fieldset.legend }}</legend>
        {% endif %}

        {% if fieldset.description %}
            <p class="description">{{ fieldset.description }}</p>
        {% endif %}

        {% for field in fieldset %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                {% include "bootstrap/field.html" %}
            {% endif %}
        {% endfor %}
    {% if not forloop.last or not fieldset_open %}
        </fieldset>
    {% endif %}
{% endfor %}

crispy_forms/templates/bootstrap/display_form.html
{% if form.form_html %}
    {% if include_media %}{{ form.media }}{% endif %}
    {% if form_show_errors %}
        {% include "bootstrap/errors.html" %}
    {% endif %}
    {{ form.form_html }}
{% else %}
    {% include "bootstrap/uni_form.html" %}
{% endif %}

crispy_forms/templates/bootstrap/errors.html
{% if form.non_field_errors %}
    <div class="alert alert-block alert-error">
        {% if form_error_title %}<h4 class="alert-heading">{{ form_error_title }}</h4>{% endif %}
        <ul>
            {{ form.non_field_errors|unordered_list }}
        </ul>
    </div>
{% endif %}

crispy_forms/templates/bootstrap/errors_formset.html
{% if formset.non_form_errors %}
    <div class="alert alert-block alert-error">
        {% if formset_error_title %}<h4 class="alert-heading">{{ formset_error_title }}</h4>{% endif %}
        <ul>
            {{ formset.non_form_errors|unordered_list }}
        </ul>
    </div>
{% endif %}

crispy_forms/templates/bootstrap/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="control-group{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} error{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            <div class="controls">
                {% if field|is_checkbox and form_show_labels %}
                    <label for="{{ field.id_for_label }}" class="checkbox {% if field.field.required %}requiredField{% endif %}">
                        {% crispy_field field %}
                        {{ field.label|safe }}
                    </label>
                    {% include 'bootstrap/layout/help_text_and_errors.html' %}
                {% else %}
                    {% crispy_field field %}
                    {% include 'bootstrap/layout/help_text_and_errors.html' %}
                {% endif %}
            </div>
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
{% endif %}

crispy_forms/templates/bootstrap/layout/alert.html
<div{% if alert.css_id %} id="{{ alert.css_id }}"{% endif %}{% if alert.css_class %} class="{{ alert.css_class }}"{% endif %}>
    {% if dismiss %}<button type="button" class="close" data-dismiss="alert">&times;</button>{% endif %}
    {{ content|safe }}
</div>

crispy_forms/templates/bootstrap/layout/button.html
<button {{ button.flat_attrs|safe }}>{{ button.content|safe }}</button>

crispy_forms/templates/bootstrap/layout/checkboxselectmultiple_inline.html
{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

        {% if field.label %}
            <label for="{{ field.auto_id }}"  class="control-label{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% include 'bootstrap/layout/checkboxselectmultiple.html' %}
    </div>
{% endif %}

crispy_forms/templates/bootstrap/layout/field_errors.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-inline"><strong>{{ error }}</strong></span>
    {% endfor %}
{% endif %}

crispy_forms/templates/bootstrap/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></p>
    {% endfor %}
{% endif %}

crispy_forms/templates/bootstrap/layout/formactions.html
<div{% if formactions.attrs %} {{ formactions.flat_attrs|safe }}{% endif %} class="form-actions">
    {{ fields_output|safe }}
</div>

crispy_forms/templates/bootstrap/layout/help_text_and_errors.html
{% if help_text_inline and not error_text_inline %}
    {% include 'bootstrap/layout/help_text.html' %}
{% endif %}

{% if error_text_inline %}
    {% include 'bootstrap/layout/field_errors.html' %}
{% else %}
    {% include 'bootstrap/layout/field_errors_block.html' %}
{% endif %}

{% if not help_text_inline %}
    {% include 'bootstrap/layout/help_text.html' %}
{% endif %}

crispy_forms/templates/bootstrap/layout/multifield.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}

    {% if field.label %}
        <label for="{{ field.id_for_label }}"{% if labelclass %} class="{{ labelclass }}"{% endif %}>
    {% endif %}

    {% if field|is_checkbox %}
        {% crispy_field field %}
    {% endif %}

    {% if field.label %}
        {{ field.label }}
    {% endif %}

    {% if not field|is_checkbox %}
        {% crispy_field field %}
    {% endif %}

    {% if field.label %}
        </label>
    {% endif %}

{% endif %}

crispy_forms/templates/bootstrap/layout/prepended_appended_text.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

        {% if field.label and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="control-label{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        <div class="controls">
            <div class="{% if crispy_prepended_text %}input-prepend{% endif %} {% if crispy_appended_text %}input-append{% endif %}">
                {% if crispy_prepended_text %}<span class="{% if not field|is_select %}add-on{% endif %}{% if active %} active{% endif %}">{{ crispy_prepended_text|safe }}</span>{% endif %}
                {% crispy_field field %}
                {% if crispy_appended_text %}<span class="{% if not field|is_select %}add-on{% endif %}{% if active %} active{% endif %}">{{ crispy_appended_text|safe }}</span>{% endif %}
            </div>

            {% include 'bootstrap/layout/help_text_and_errors.html' %}
        </div>
    </div>
{% endif %}

crispy_forms/templates/bootstrap/layout/radioselect.html
{% load crispy_forms_filters %}
{% load l10n %}

<div class="controls"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>
    {% include 'bootstrap/layout/field_errors_block.html' %}

    {% for choice in field.field.choices %}
        <label class="radio{% if inline_class %} {{ inline_class }}{% endif %}">
            <input type="radio"{% if choice.0|stringformat:"s" == field.value|stringformat:"s" %} checked="checked"{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter }}" value="{{ choice.0|unlocalize }}" {{ field.field.widget.attrs|flatatt }}>{{ choice.1|unlocalize }}
        </label>
    {% endfor %}

    {% include 'bootstrap/layout/help_text.html' %}
</div>

crispy_forms/templates/bootstrap/layout/radioselect_inline.html
{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

        {% if field.label %}
            <label for="{{ field.auto_id }}"  class="control-label{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% include 'bootstrap/layout/radioselect.html' %}
    </div>
{% endif %}

crispy_forms/templates/bootstrap/layout/tab-link.html
<li class="tab-pane{% if 'active' in link.css_class %} active{% endif %}"><a href="#{{ link.css_id }}" data-toggle="tab">{{ link.name|capfirst }}{% if tab.errors %}!{% endif %}</a></li>

crispy_forms/templates/bootstrap/layout/tab.html
<ul{% if tabs.css_id %} id="{{ tabs.css_id }}"{% endif %} class="nav nav-tabs">
    {{ links|safe }}
</ul>
<div class="tab-content">
    {{ content|safe }}
</div>

crispy_forms/templates/bootstrap/layout/uneditable_input.html
<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
    <div class="control-label{% if field.field.required %} requiredField{% endif %}">{{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}</div>
    <div class="controls">
        <span {{ flat_attrs|safe }}>{% if field.value %}{{ field.value }}{% endif %}</span>
        {% include 'bootstrap/layout/help_text.html' %}
    </div>
</div>

crispy_forms/templates/bootstrap/table_inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table table-striped table-condensed">
        <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th for="{{ field.auto_id }}" class="control-label {% if field.field.required and not field|is_checkbox %}requiredField{% endif %}">
                                {{ field.label|safe }}{% if field.field.required and not field|is_checkbox %}<span class="asteriskField">*</span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endif %}
        </thead>

        <tbody>
            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "bootstrap/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                        {% include 'bootstrap/field.html' with tag="td" form_show_labels=False %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "bootstrap/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

crispy_forms/templates/bootstrap/uni_form.html
{% load crispy_forms_utils %}

{% specialspaceless %}
    {% if include_media %}{{ form.media }}{% endif %}
    {% if form_show_errors %}
        {% include "bootstrap/errors.html" %}
    {% endif %}
    {% for field in form %}
        {% include "bootstrap/field.html" %}
    {% endfor %}
{% endspecialspaceless %}

crispy_forms/templates/bootstrap/uni_formset.html
{% with formset.management_form as form %}
    {% include 'bootstrap/uni_form.html' %}
{% endwith %}
{% for form in formset %}
    <div class="multiField">
        {% include 'bootstrap/uni_form.html' %}
    </div>
{% endfor %}

crispy_forms/templates/bootstrap/whole_uni_form.html
{% load crispy_forms_utils %}

{% specialspaceless %}
{% if form_tag %}<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>{% endif %}
    {% if form_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    {% include "bootstrap/display_form.html" %}

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "bootstrap/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if form_tag %}</form>{% endif %}
{% endspecialspaceless %}

crispy_forms/templates/bootstrap/whole_uni_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

    {% include "bootstrap/errors_formset.html" %}

    {% for form in formset %}
        {% include "bootstrap/display_form.html" %}
    {% endfor %}

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "bootstrap/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

crispy_forms/templates/bootstrap3/accordion-group.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#{{ div.data_parent }}" href="#{{ div.css_id }}">{{ div.name }}</a>
        </h4>
    </div>
    <div id="{{ div.css_id }}" class="panel-collapse collapse{% if div.active %} in{% endif %}" >
        <div class="panel-body">
            {{ fields|safe }}
        </div>
    </div>
</div>

crispy_forms/templates/bootstrap3/accordion.html
<div class="panel-group" id="{{ accordion.css_id }}">
    {{ content|safe }}
</div>

crispy_forms/templates/bootstrap3/betterform.html
{% for fieldset in form.fieldsets %}
    <fieldset class="fieldset-{{ forloop.counter }} {{ fieldset.classes }}">
        {% if fieldset.legend %}
            <legend>{{ fieldset.legend }}</legend>
        {% endif %}

        {% if fieldset.description %}
            <p class="description">{{ fieldset.description }}</p>
        {% endif %}

        {% for field in fieldset %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                {% include "bootstrap3/field.html" %}
            {% endif %}
        {% endfor %}
    {% if not forloop.last or not fieldset_open %}
        </fieldset>
    {% endif %}
{% endfor %}

crispy_forms/templates/bootstrap3/display_form.html
{% if form.form_html %}
    {{ form.media }}
    {% if form_show_errors %}
        {% include "bootstrap3/errors.html" %}
    {% endif %}
    {{ form.form_html }}
{% else %}
    {% include "bootstrap3/uni_form.html" %}
{% endif %}

crispy_forms/templates/bootstrap3/errors.html
{% if form.non_field_errors %}
    <div class="alert alert-block alert-danger">
        {% if form_error_title %}<h4 class="alert-heading">{{ form_error_title }}</h4>{% endif %}
        <ul>
            {{ form.non_field_errors|unordered_list }}
        </ul>
    </div>
{% endif %}

crispy_forms/templates/bootstrap3/errors_formset.html
{% if formset.non_form_errors %}
    <div class="alert alert-block alert-danger">
        {% if formset_error_title %}<h4 class="alert-heading">{{ formset_error_title }}</h4>{% endif %}
        <ul>
            {{ formset.non_form_errors|unordered_list }}
        </ul>
    </div>
{% endif %}

crispy_forms/templates/bootstrap3/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% else %}class="{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-error{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap3/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap3/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap3/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="controls {{ field_class }}">
                	{% if field.label == "Delete" %}
                		<a class="btn btn-danger detail_delete" href="javascript:void(0)" id="{{field.auto_id}}">{{field.label}}</a>
                	{% else %}
                    	{% crispy_field field %}
                    	{% include 'bootstrap3/layout/help_text_and_errors.html' %}
                    {% endif %}
                </div>
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

crispy_forms/templates/bootstrap3/inputs.html
{% if inputs %}
    <div class="form-group">
        {% if label_class %}
            <div class="aab controls {{ label_class }}"></div>
        {% endif %}

        <div class="controls {{ field_class }}">
            {% for input in inputs %}
                {% include "bootstrap3/layout/baseinput.html" %}
            {% endfor %}
        </div>
    </div>
{% endif %}

crispy_forms/templates/bootstrap3/layout/alert.html
<div{% if alert.css_id %} id="{{ alert.css_id }}"{% endif %}{% if alert.css_class %} class="{{ alert.css_class }}"{% endif %}>
    {% if dismiss %}<button type="button" class="close" data-dismiss="alert">&times;</button>{% endif %}
    {{ content|safe }}
</div>

crispy_forms/templates/bootstrap3/layout/button.html
<button {{ button.flat_attrs|safe }}>{{ button.content|safe }}</button>

crispy_forms/templates/bootstrap4/accordion.html
<div class="panel-group" id="{{ accordion.css_id }}">
    {{ content|safe }}
</div>

recruit_app/templates/admin_recruit_application_list.html
{% extends 'page_layout.html' %}
{% load crispy_forms_tags %} 
{% block body_header %}{% endblock %}
{% block body_content %}
<div class="row">
	<div class="col-xs-12 col-md-12 text-center" style="margin-top:2%;">
		<h3>Application list</h3>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th style="width:20%">Name</th>
					<th style="width:20%">Email</th>
					<th style="width:20%">Phone</th>
					<th style="width:10%">Years of Experience</th>
					<th style="width:30%">Status</th>
				</tr>
			</thead>
  			<tbody>
  				{% for application in recruit_applications %}
  				<tr>
  					<td>{{application.name}}</td>
  					<td>{{application.email}}</td>
  					<td>{{application.phone}}</td>
  					<td>{{application.years_of_experience}}</td>
  					<td id="id_td_{{application.id}}">
  					{% if application.status == "PENDING" %}
  						<button type="button" class="btn btn-success" onclick="javascript:update_application_status('{{application.id}}', 'APPROVED')">Approve</button> &nbsp;&nbsp;
  						<button type="button" class="btn btn-warning" onclick="javascript:update_application_status('{{application.id}}', 'REJECTED')">Reject</button>
  					{% else %}
  						{{application.get_status_display}}
  					{% endif %}
  					</td>
  					
  				</tr>
  				{% endfor %}
  			</tbody>
		</table>
	</div>
</div>

{% endblock %}
{% block body_footer %}
<script type="text/javascript">

	function update_application_status(application_id, status){
		$.ajax({
			type : 'POST',
			data: {'csrfmiddlewaretoken' : "{{csrf_token}}", "application_id":application_id, "status":status },
			url : "{% url 'admin_recruit_application_update_status' %}",
			complete : function(xhr) {
				jsonstr = xhr.responseText;
            	jsonObj = jQuery.parseJSON(jsonstr);
            	if(jsonObj.result){
            		$("#id_td_"+application_id).html(jsonObj.response_text);	
            	}
            	else{
            		alert("Error, Please Try Again!.")
            	}
			    
			}
		});
	}
</script>
{% endblock %}